"""add org clerk_id

Revision ID: 25ef374ca631
Revises: 1641d47d0692
Create Date: 2026-07-31 19:39:36.378794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ef374ca631'
down_revision: Union[str, None] = '1641d47d0692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('clerk_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_organizations_clerk_id'), 'organizations', ['clerk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_clerk_id'), table_name='organizations')
    op.drop_column('organizations', 'clerk_id')
    # ### end Alembic commands ###
